apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-task
  template:
    metadata:
      labels:
        app: python-task
    spec:
      containers:
        - name: python-task
          image: syedashraf123/brine-task-python
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
